name: deepgsb
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - scipy
  - termcolor
  - easydict
  - ipdb
  - pytorch==1.11.0
  - torchvision
  - cudatoolkit=10.2
  - tqdm
  - scikit-learn
  - imageio
  - matplotlib
  - tensorboard
  - pip
  - pip:
    - colored-traceback
    - torch-ema
    - gdown
    - rich
    - geomloss